name: Juntos CI

# For every push on every branch/PR
on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: setup
      run: |
        sudo apt-get update
        sudo apt install cmake llvm-16
    - name: compile
      run: |
        rm -Rf build/
        mkdir build/
        cd build/
        cmake ..
        make